last_update = 1733438762998
api_url = "https://api.playit.cloud/agent"
ping_target_addresses = []
control_address = "control.playit.gg"
refresh_from_api = true
api_refresh_rate = 5000
ping_interval = 5000
secret_key = "f4e6feac8cb89838a6878dd7b01a0b2387159db48be5369c9193c451227a537c"

[[mappings]]
name = "unnamed"
proto = "both"
tunnel_ip = "147.185.221.17"
tunnel_from_port = 16244
local_ip = "192.168.0.4"
local_port = 4000

[[mappings]]
name = "unnamed"
proto = "both"
tunnel_ip = "147.185.221.16"
tunnel_from_port = 47790
local_ip = "192.168.0.4"
local_port = 3306

[[mappings]]
name = "Minecraft Java"
proto = "tcp"
tunnel_ip = "147.185.221.223"
tunnel_from_port = 59351
local_port = 51335
